name: Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build Core Jar
      run: mvn -B -q install --file vripper-core/pom.xml

    - name: Build GUI Jar
      run: mvn -B -q install --file vripper-gui/pom.xml

    - if: matrix.os == 'ubuntu-latest'
      name: Build WEB Jar
      run: |
        mvn -B -q install --file vripper-web-ui/pom.xml
        mvn -B -q install --file vripper-web/pom.xml

    - name: Rename GUI Jar
      run: mv vripper-gui/target/vripper-gui-*.jar vripper-gui/target/vripper-gui.jar

    - if: matrix.os == 'ubuntu-latest'
      name: Upload GUI Jar
      uses: softprops/action-gh-release@v1
      with:
        files: vripper-gui/target/vripper-gui.jar

    - if: matrix.os == 'ubuntu-latest'
      name: Rename WEB Jar
      run: mv vripper-web/target/vripper-web-*.jar vripper-web/target/vripper-web.jar

    - if: matrix.os == 'ubuntu-latest'
      name: Upload WEB Jar
      uses: softprops/action-gh-release@v1
      with:
        files: vripper-web/target/vripper-web.jar

    - name: Prepare Packaging
      run: |
        cp vripper-gui/target/vripper-gui.jar jpackage/jar/vripper-gui.jar
        
    - if: matrix.os == 'ubuntu-latest'
      name: Package Linux
      run: |
        cd jpackage
        jpackage --app-version ${{ github.event.release.tag_name }} --type deb "@jpackage.cfg" "@jpackage-linux.cfg"
        jpackage --app-version ${{ github.event.release.tag_name }} --type rpm "@jpackage.cfg" "@jpackage-linux.cfg"

    - if: matrix.os == 'ubuntu-latest'
      name: Upload DEB and RPM package for Linux
      uses: softprops/action-gh-release@v1
      with:
        files: |
          jpackage/dist/vripper-${{ github.event.release.tag_name }}-1.x86_64.rpm
          jpackage/dist/vripper_${{ github.event.release.tag_name }}-1_amd64.deb

    - if: matrix.os == 'windows-latest'
      name: Package Windows
      run: |
        cd jpackage
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-windows.cfg"

    - if: matrix.os == 'windows-latest'
      name: Upload packages for Windows
      uses: softprops/action-gh-release@v1
      with:
        files: jpackage/dist/VRipper-${{ github.event.release.tag_name }}.msi

    - if: matrix.os == 'macos-latest'
      name: Package macOS
      run: |
        cd jpackage
        jpackage --app-version ${{ github.event.release.tag_name }} "@jpackage.cfg" "@jpackage-macos.cfg"

    - if: matrix.os == 'macos-latest'
      name: Upload package for macOS
      uses: softprops/action-gh-release@v1
      with:
        files: jpackage/dist/VRipper-${{ github.event.release.tag_name }}.pkg